version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.24
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-export-command: &export-cmd
  entrypoint: ["node_modules/.bin/basecms-exports"]
  command: ["dev", "index.js"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://virgon.graphql.base.parameter1.com}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  abmedia:
    <<: *node
    <<: *export-cmd
    working_dir: /root/tenants/abmedia
    environment:
      <<: *env
      <<: *env-virgon
      PORT: 80
      EXPOSED_PORT: 19400
      LIVERELOAD_PORT: 29400
      TENANT_KEY: abmedia_all
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "19400:80"
      - "29400:29400"

  minexpo:
    <<: *node
    <<: *export-cmd
    working_dir: /root/tenants/minexpo
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 19500
      LIVERELOAD_PORT: 29500
      TENANT_KEY: ascend_minex
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "19500:80"
      - "29500:29500"

volumes:
  yarn-cache: {}
